version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install gfortran g++ gcc
      - run: cmake . && make -j8
      - run: cd run/; echo "Reference.ini" | ./Evolution; cd ..;
      - run: cd run/; echo "Reference.ini" | ./Timing; cd ..;
      - run: cd run/; echo "Reference.ini" | ./StructureFunctions; cd ..;
