#
# Configuration file. Comments start with #.
#
# If any of the following parameters is missing or commented out,
# the default value will be used.
#
#########################################
# Evolution parameters			#
#########################################
IPT      = 1				# Perturbative order (0,1,2)
MODEV    = "ITE"			# Solution of the DGLAP equation ("ITE", "TRN", "PTH", "GFN")
NS       = "VFNS"			# Mass scheme used for the LHA evoultion ("VFNS","FFNS")
NFMAX    = 5				# Maximum number of flavours for the LHA evolution (3,4,5,6)
NFFN     = 5				# Number of active flavours in the FFNS (3,4,5,6)
HQMASS   = "MSBAR"			# Heavy quark mass scheme ("POLE","MSBAR")
KRF      = 1d0				# muR / muF
EVOL     = "TIME"			# Evolution ("SPACE" = space-like (PDFs),"TIME" = time-like (FFs))
POL      = "OFF"	                # Polarization of the evolution ("OFF" = unpolarized, "ON" = polarized)
DISTF    = "d4g3S11"			# Distribution function
# options "deltagNLO","deltag","pwave0","pwave1","pwave2","c3s11LO","c3s11NLO", "constant", "Gc3S11","Fc3S11""g3s18MA"
#"d0g3S11" ; "c3S11LO"; g3S11c0
# FENG FENG : FENGg3S11
# full FF3S11
# full FF3S11v4
# full FF3S11c c
# full FF3S11g g
#########################################
# Coupling				#
#########################################
QREF     = 91.1876d0, 0d0	# Reference scale for alpha_s [GeV]
ASREF    = 0.118d0, 0d0			# alpha_s at the refence scale
#########################################
# Heavy quark masses			#
#########################################
MC       = 1.5d0		# Charm threshold  [GeV]
MB       = 4.5d0			# Bottom threshold [GeV]
MT       = 175d0 			# Top threshold    [GeV]
#########################################
# DIS					#
#########################################
PROC     = "NC"				# DIS process ("EM", "NC")
KRENQ    = 1.0d0			# muR / Q
KFACQ    = 1.0d0			# muF / Q
#########################################
# LHAPDF grid parameters		#
#########################################
NXLHA    = 300                          # Number of x-space grid nodes
NXMLHA   = 150                          # Number of log x-space nodes
NQ2LHA   = 200                          # Number of Q-space grid nodes
Q2MINLHA = 9D0                          # Q2 lower bound
Q2MAXLHA = 10D4                         # Q2 upper bound
XMINLHA  = 1D-5                         # x lower bound
XMLHA    = 3D-1                         # x transition point
XMAXLHA  = 0.99999999999999D0          # x upper bound
#########################################
#########################################
